# A goPen yaml config

variables:
  addresses: 192.168.10.1
  ports: 80
  root: false

workflow:
  nmap:
    executable: /usr/sbin/nmap
    flags: -Pn

  gobuster:
    executable: /usr/sbin/gobuster
    flags: ""
