# A goPen yaml config

variables:
  threads: 64
  addresses: 192.168.1.1/24
  ports: 80
  root: false

workflow:
  nmap:
    executable: /usr/sbin/nmap
    flags: -Pn

  gobuster:
    executable: /usr/sbin/gobuster
    flags: ""
